# Generated by Django 5.1 on 2024-08-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employ',
        ),
    ]
