# Generated by Django 5.1 on 2024-08-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0002_rename_employee_employ'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employ',
            new_name='user_table',
        ),
    ]
