# Generated by Django 5.1 on 2024-08-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0003_rename_employ_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_table',
            name='department',
        ),
    ]
