# Generated by Django 5.1 on 2024-08-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0004_remove_user_table_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
