# Generated by Django 5.1 on 2024-08-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0005_user_table_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
